# Generated by Django 3.1.2 on 2021-09-02 23:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber_gallery',
            name='haircut_name',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='client_phone',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_desired_hair_cut', models.CharField(blank=True, default='', max_length=50)),
                ('barber_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.barber')),
                ('client_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.client')),
            ],
        ),
    ]
