# Generated by Django 3.1.2 on 2021-09-06 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20210906_0822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='barber_hairCuts',
        ),
        migrations.AddField(
            model_name='barber_gallery',
            name='barber_name',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='booking.barber'),
            preserve_default=False,
        ),
    ]
