# Generated by Django 3.1.2 on 2021-09-13 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_auto_20210906_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='client_phone_number',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='appointment',
            name='when',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=200),
        ),
    ]
