# Generated by Django 3.1.2 on 2021-09-14 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('barbers_accounts', '0001_initial'),
        ('booking', '0005_auto_20210913_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber_gallery',
            name='barber_name',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='barber_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbers_accounts.barber'),
        ),
        migrations.DeleteModel(
            name='barber',
        ),
        migrations.DeleteModel(
            name='barber_gallery',
        ),
    ]
