# Generated by Django 3.1.2 on 2021-09-14 03:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('booking', '0006_auto_20210913_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='barber_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
