# Generated by Django 3.1.2 on 2021-09-20 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_auto_20210913_2302'),
    ]

    operations = [
        migrations.DeleteModel(
            name='client',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='client_phone_number',
            field=models.CharField(blank=True, default='', max_length=50, unique=True),
        ),
    ]
