# Generated by Django 3.1.2 on 2021-09-20 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_auto_20210920_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_phone_number',
            field=models.CharField(blank=True, default='', max_length=50, null=True, unique=True),
        ),
    ]
