# Generated by Django 3.1.2 on 2021-09-20 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_appointment_appointment_statue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_statue',
            field=models.CharField(choices=[('waiting', 'ينتظر'), ('in progress', 'يعمل على قصة شعره'), ('finished', 'انتهى'), ('did not show up', 'لم يحضر')], default='waiting', max_length=20),
        ),
    ]
