# Generated by Django 3.1.2 on 2021-09-20 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_auto_20210920_0214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_statue',
            field=models.CharField(choices=[('ينتظر', 'ينتظر'), ('يعمل على قصة شعره', 'يعمل على قصة شعره'), ('انتهى', 'انتهى'), ('لم يحضر', 'لم يحضر')], default=('ينتظر', 'ينتظر'), max_length=20),
        ),
    ]
