# Generated by Django 3.1.2 on 2021-09-21 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_auto_20210920_0216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_statue',
            field=models.CharField(choices=[('ينتظر', 'ينتظر'), ('يعمل على قصة شعره', 'يعمل على قصة شعره'), ('انتهى', 'انتهى'), ('لم يحضر', 'لم يحضر')], default='ينتظر', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='when',
            field=models.DateField(default=datetime.date(2021, 9, 21)),
        ),
    ]
