# Generated by Django 3.1.2 on 2021-09-30 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_auto_20210922_0531'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='client_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='when',
            field=models.DateField(default=datetime.date(2021, 9, 30)),
        ),
    ]
