# Generated by Django 3.1.2 on 2021-09-30 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_auto_20210930_0242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='when',
            field=models.DateField(default='2021-09-30'),
        ),
    ]
