# Generated by Django 3.1.2 on 2021-09-14 01:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='barber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barber_age', models.CharField(max_length=2)),
                ('barber_phone', models.CharField(max_length=100)),
                ('barber_email', models.EmailField(max_length=254)),
                ('barber_pic', models.ImageField(blank=True, default='', upload_to='')),
                ('barber_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='barber_gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('haircut_name', models.CharField(blank=True, default='', max_length=200)),
                ('hairCuts', models.ImageField(upload_to='')),
                ('barber_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbers_accounts.barber')),
            ],
        ),
    ]
