# Generated by Django 3.1.2 on 2021-09-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers_accounts', '0002_auto_20210914_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='website_salon_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('website_logo', models.CharField(blank=True, default='', max_length=100)),
                ('website_home_picture', models.ImageField(blank=True, default='', upload_to='')),
                ('website_salon_address', models.CharField(blank=True, default='', max_length=300)),
                ('website_hair_service_1', models.CharField(blank=True, default='', max_length=300)),
                ('website_hair_service_2', models.CharField(blank=True, default='', max_length=300)),
                ('website_hair_service_3', models.CharField(blank=True, default='', max_length=300)),
                ('website_hair_service_4', models.CharField(blank=True, default='', max_length=300)),
            ],
        ),
        migrations.AddField(
            model_name='barber',
            name='barber_facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='barber',
            name='barber_instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
