# Generated by Django 3.1.2 on 2021-09-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbers_accounts', '0005_auto_20210921_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='website_salon_details',
            name='website_home_picture',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
        migrations.AlterField(
            model_name='website_salon_details',
            name='website_logo',
            field=models.ImageField(blank=True, default='', upload_to=''),
        ),
    ]
